# Generated by Django 2.2.17 on 2020-12-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoFiles',
            new_name='VideoFile',
        ),
    ]
