# Generated by Django 2.2.17 on 2020-12-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0002_auto_20201209_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='file',
            field=models.FileField(null=True, upload_to='../DjangoProject/media'),
        ),
    ]
