# Generated by Django 2.2.17 on 2020-12-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0003_auto_20201208_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videofile',
            old_name='file',
            new_name='Video_file',
        ),
    ]
