# Generated by Django 2.2.17 on 2020-12-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaApp', '0004_auto_20201208_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofile',
            name='Video_file',
            field=models.FileField(null=True, upload_to='../media'),
        ),
    ]
