name: ciworkflow
on: [push]
jobs:
  check-os-version:
    runs-on: ubuntu-latest
    steps:
      - run: uname -v
  build-pa1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          pip install -r requirements.txt
          python ./DjangoProject/manage.py runserver
        working-directory: ./
